#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_cs
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="filter")]
	public partial class filterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public filterDataContext() : 
				base(global::Diploma_cs.Properties.Settings.Default.filterConnectionStringNote, mappingSource)
		{
			OnCreated();
		}
		
		public filterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public filterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public filterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public filterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblbilateral> tblbilaterals
		{
			get
			{
				return this.GetTable<tblbilateral>();
			}
		}
		
		public System.Data.Linq.Table<tblhpf> tblhpfs
		{
			get
			{
				return this.GetTable<tblhpf>();
			}
		}
		
		public System.Data.Linq.Table<tbllpf> tbllpfs
		{
			get
			{
				return this.GetTable<tbllpf>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.add_b_res")]
		public int add_b_res([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> h, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> wc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> pt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> w, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> ss, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> si)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), h, wc, pt, w, ss, si);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.add_h_res")]
		public int add_h_res([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> h, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> wc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> pt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> perc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), h, wc, pt, perc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.add_l_res")]
		public int add_l_res([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> h, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> wc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> pt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> perc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), h, wc, pt, perc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.b_max", IsComposable=true)]
		public System.Nullable<double> b_max()
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.b_min", IsComposable=true)]
		public System.Nullable<double> b_min()
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblbilateral")]
	public partial class tblbilateral
	{
		
		private int _height;
		
		private double _width_c;
		
		private double _p_time;
		
		private System.Nullable<double> _window;
		
		private System.Nullable<double> _sigma_s;
		
		private System.Nullable<double> _sigma_i;
		
		public tblbilateral()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Int NOT NULL")]
		public int height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this._height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_width_c", DbType="Float NOT NULL")]
		public double width_c
		{
			get
			{
				return this._width_c;
			}
			set
			{
				if ((this._width_c != value))
				{
					this._width_c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_time", DbType="Float NOT NULL")]
		public double p_time
		{
			get
			{
				return this._p_time;
			}
			set
			{
				if ((this._p_time != value))
				{
					this._p_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_window", DbType="Float")]
		public System.Nullable<double> window
		{
			get
			{
				return this._window;
			}
			set
			{
				if ((this._window != value))
				{
					this._window = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sigma_s", DbType="Float")]
		public System.Nullable<double> sigma_s
		{
			get
			{
				return this._sigma_s;
			}
			set
			{
				if ((this._sigma_s != value))
				{
					this._sigma_s = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sigma_i", DbType="Float")]
		public System.Nullable<double> sigma_i
		{
			get
			{
				return this._sigma_i;
			}
			set
			{
				if ((this._sigma_i != value))
				{
					this._sigma_i = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblhpf")]
	public partial class tblhpf
	{
		
		private int _height;
		
		private double _width_c;
		
		private double _p_time;
		
		private double _perc;
		
		public tblhpf()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Int NOT NULL")]
		public int height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this._height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_width_c", DbType="Float NOT NULL")]
		public double width_c
		{
			get
			{
				return this._width_c;
			}
			set
			{
				if ((this._width_c != value))
				{
					this._width_c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_time", DbType="Float NOT NULL")]
		public double p_time
		{
			get
			{
				return this._p_time;
			}
			set
			{
				if ((this._p_time != value))
				{
					this._p_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perc", DbType="Float NOT NULL")]
		public double perc
		{
			get
			{
				return this._perc;
			}
			set
			{
				if ((this._perc != value))
				{
					this._perc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbllpf")]
	public partial class tbllpf
	{
		
		private int _height;
		
		private double _width_c;
		
		private double _p_time;
		
		private double _perc;
		
		public tbllpf()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="Int NOT NULL")]
		public int height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this._height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_width_c", DbType="Float NOT NULL")]
		public double width_c
		{
			get
			{
				return this._width_c;
			}
			set
			{
				if ((this._width_c != value))
				{
					this._width_c = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_time", DbType="Float NOT NULL")]
		public double p_time
		{
			get
			{
				return this._p_time;
			}
			set
			{
				if ((this._p_time != value))
				{
					this._p_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perc", DbType="Float NOT NULL")]
		public double perc
		{
			get
			{
				return this._perc;
			}
			set
			{
				if ((this._perc != value))
				{
					this._perc = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
